"""
Problem 2
---------
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def bruteforce(threshold):
    fibonaccis = [1,2]
    n1 = 1
    n2 = 2
    evens_sum = 2
    while n1+n2 < threshold:
        n3 = n1+n2
        if n3 % 2 == 0:
            evens_sum = evens_sum + n3
        fibonaccis.append(n3)
        n1 = n2
        n2 = n3
    return evens_sum

print("brute force")
print(bruteforce(100))
print(bruteforce(4000000))
