"""
Problem #12
----------------
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:
 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""

def triangleNumber(min_divisor_count):
    n = 1
    trin = 1
    while True:
        #check if trin has enough divisors
        num_divisors = 1
        for i in range(2,trin//2+1):
            if trin % i ==0:
                num_divisors+=1
                if num_divisors>=min_divisor_count:
                    return trin
        #calculate the next triangle number and try again
        n+=1
        trin+=n

print(triangleNumber(5))
print(triangleNumber(500))
