"""
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
"""

pentagon_numbers = set({n*(3*n-1)//2 for n in range(1,10**4)})
sol_set = set({})

for p1 in pentagon_numbers:
    for p2 in pentagon_numbers:
        if p1-p2 in pentagon_numbers and p1+p2 in pentagon_numbers:
            sol_set.add((p1,p2,abs(p1-p2)))

print(sol_set)
