"""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.
Find the next triangle number that is also pentagonal and hexagonal.
"""

triangle_numbers = set({n*(n+1)//2 for n in range(1,10**6)})
pentagonal_numbers = set({n*(3*n-1)//2 for n in range(1,10**6)})
hexagonal_numbers = set({n*(2*n-1) for n in range(1,10**6)})
# print(triangle_numbers)
# print(pentagonal_numbers)
# print(hexagonal_numbers)

for n in sorted(triangle_numbers):
    if n in pentagonal_numbers and n in hexagonal_numbers:
        print(n)